### PR TITLE
Remove file extension check

### LINKED ISSUE #15: Extension check issue
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
At study creation, extensions is check and is supposed to match format name.
Is cannot work as extensions and format are 2 different things. Sometime we support several extensions for one format. Also sometime extension is not related to format (like zip for CGMES)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
For instance just try to import a CGMES (.zip)

* **What is the expected behavior?**
Extension must not be checked on client side.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by ChamseddineBhd**
Signed-off-by: ChamseddineBhd <chamseddine.benhamed@ensi-uma.tn>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Fix #15 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: src/utils/rest-api.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ export function createStudy(caseExist, studyName, studyDescription, caseName, se
         const createStudyWithNewCaseUrl = process.env.REACT_APP_API_STUDY_SERVER + "/v1/studies/" + studyName + "?description=" + studyDescription;
         const formData = new FormData();
         formData.append('caseFile', selectedFile);
-        console.debug("selectedFile: " + selectedFile);
+        console.debug("selectedFile: " + selectedFile.name);
```
Comment (geofjamg) [inline src/utils/rest-api.js]: Was it just for temp debugging? if yes, we should remove it.
